### ISSUE TITLE
amazing is the pre-train models going to be released? 

### ISSUE THREAD

**Issue by JaeDukSeo** [azmiozgen/text2painting#1]
amazing is the pre-train models going to be released?

**Comment by azmiozgen** [comment]
The model size is quite large. It soon will be shared from an external source though.

**Comment by ghost** [comment]
@azmiozgen google drive might work for storing the models

**Comment by azmiozgen** [comment]
> @azmiozgen google drive might work for storing the models

Yep. Probably will share from there.

**Comment by azmiozgen** [comment]
See updated README.md
